stages:
    - build
    - deploy
    - delete

build:
    stage: build
    variables:
        GIT_STRATEGY: clone
    script:
        - echo "Build nodeapp to docker image"
        - docker login -u rizkypanz -p Rizkypanji16
        - docker build -f Dockerfile -t rizkypanz/hellonodejs:stable .
        - docker push rizkypanz/hellonodejs:stable
    only:
        variables:
            - $CI_COMMIT_MESSAGE =~ /build/
    tags:
        - gitlab-runner
deploy:
    stage: deploy
    variables:
        GIT_STRATEGY: clone
    script:
        - echo "Run kubectl on gitlab-runner"
        - kubectl get nodes
        - kubectl apply -f deployment-nodeapp.yaml
        - kubectl get all -n belajar
    only:
        variables:
            - $CI_COMMIT_MESSAGE =~ /deploy/
            - $CI_COMMIT_MESSAGE =~ /build & deploy/
    tags:
        - gitlab-runner
delete:
    stage: delete
    variables:
        GIT_STRATEGY: clone
    script:
        - echo "Delete kubernetes deployment"
        - kubectl delete -f deployment-nodeapp.yaml
        - kubectl get all -n belajar
        - echo "Delete docker image"
        - docker rmi rizkypanz/hellonodejs:stable
        - docker images
    only:
        variables:
            - $CI_COMMIT_MESSAGE =~ /delete/
    tags:
        - gitlab-runner
